#!/usr/bin/env python

import sys, os
import numpy as np
import scipy.io
from lmmdm import optimize_metric
from Emsmbuilder import arglib

parser = arglib.ArgumentParser(description='3D Random Walker')
parser.add_argument('output', description='Location to save output (.dat)', default='Traj.dat')
parser.add_argument('x_step', type=float)
parser.add_argument('y_step', type=float)
parser.add_argument('z_step', type=float)
parser.add_argument('length', type=int)
args = parser.parse_args()

steps = np.array(2*np.random.randint(2, size=(args.length-1, 3)) - 1, dtype='float')
steps[:,0] *= args.x_step
steps[:,1] *= args.y_step
steps[:,2] *= args.z_step
traj = np.vstack(([0,0,0], np.cumsum(steps, axis=0)))

np.savetxt(args.output, traj)
print '\nSaved {0}'.format(args.output)